-- Mental Trainer Supabase schema
-- Run this script in Supabase SQL Editor.

create extension if not exists pgcrypto;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.user_migrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  migration_key text not null,
  metadata jsonb not null default '{}'::jsonb,
  migrated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, migration_key)
);

create table if not exists public.user_gamification_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  streak_count integer not null default 0 check (streak_count >= 0),
  streak_last_date date null,
  total_score integer not null default 0 check (total_score >= 0),
  last_synced_math_score integer not null default 0 check (last_synced_math_score >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_daily_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null,
  activity_count integer not null default 0 check (activity_count >= 0),
  module_counts jsonb not null default '{}'::jsonb check (jsonb_typeof(module_counts) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, activity_date)
);

create table if not exists public.user_formula_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  formula_id text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, formula_id)
);

create table if not exists public.user_dictionary_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  last_searched_at timestamptz not null default timezone('utc', now()),
  search_count integer not null default 1 check (search_count >= 1),
  unique (user_id, word)
);

create table if not exists public.user_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  app_key text not null,
  settings jsonb not null default '{}'::jsonb check (jsonb_typeof(settings) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, app_key)
);

create table if not exists public.math_trainer_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_hash text not null,
  mode text not null,
  correct integer not null default 0 check (correct >= 0),
  total integer not null default 0 check (total >= 0),
  accuracy numeric(5, 2) not null default 0,
  avg_time numeric(12, 4) null,
  best_time numeric(12, 4) null,
  session_timestamp timestamptz not null default timezone('utc', now()),
  times jsonb not null default '[]'::jsonb check (jsonb_typeof(times) = 'array'),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, event_hash)
);

create table if not exists public.math_trainer_solve_times (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_hash text not null,
  mode text not null,
  solve_time numeric(12, 4) not null check (solve_time >= 0),
  solve_timestamp timestamptz not null default timezone('utc', now()),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, event_hash)
);

create table if not exists public.math_trainer_wrong_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_hash text not null,
  problem text not null,
  user_answer text null,
  correct_answer text null,
  operation text null,
  answered_at timestamptz not null default timezone('utc', now()),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, event_hash)
);

create table if not exists public.user_module_state (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_key text not null,
  state jsonb not null default '{}'::jsonb check (jsonb_typeof(state) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, module_key)
);

create index if not exists idx_user_daily_activity_user_date
  on public.user_daily_activity(user_id, activity_date desc);

create index if not exists idx_dictionary_history_user_last
  on public.user_dictionary_history(user_id, last_searched_at desc);

create index if not exists idx_math_trainer_sessions_user_ts
  on public.math_trainer_sessions(user_id, session_timestamp desc);

create index if not exists idx_math_trainer_sessions_user_mode_ts
  on public.math_trainer_sessions(user_id, mode, session_timestamp desc);

create index if not exists idx_math_trainer_solve_times_user_ts
  on public.math_trainer_solve_times(user_id, solve_timestamp desc);

create index if not exists idx_math_trainer_solve_times_user_mode_ts
  on public.math_trainer_solve_times(user_id, mode, solve_timestamp desc);

create index if not exists idx_math_trainer_wrong_answers_user_ts
  on public.math_trainer_wrong_answers(user_id, answered_at desc);

create index if not exists idx_math_trainer_wrong_answers_user_operation_ts
  on public.math_trainer_wrong_answers(user_id, operation, answered_at desc);

create index if not exists idx_user_module_state_user_updated
  on public.user_module_state(user_id, updated_at desc);

drop trigger if exists trg_user_gamification_stats_updated_at on public.user_gamification_stats;
create trigger trg_user_gamification_stats_updated_at
before update on public.user_gamification_stats
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists trg_user_daily_activity_updated_at on public.user_daily_activity;
create trigger trg_user_daily_activity_updated_at
before update on public.user_daily_activity
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
before update on public.user_settings
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists trg_user_module_state_updated_at on public.user_module_state;
create trigger trg_user_module_state_updated_at
before update on public.user_module_state
for each row execute function public.set_current_timestamp_updated_at();

alter table public.user_migrations enable row level security;
alter table public.user_migrations force row level security;

alter table public.user_gamification_stats enable row level security;
alter table public.user_gamification_stats force row level security;

alter table public.user_daily_activity enable row level security;
alter table public.user_daily_activity force row level security;

alter table public.user_formula_favorites enable row level security;
alter table public.user_formula_favorites force row level security;

alter table public.user_dictionary_history enable row level security;
alter table public.user_dictionary_history force row level security;

alter table public.user_settings enable row level security;
alter table public.user_settings force row level security;

alter table public.math_trainer_sessions enable row level security;
alter table public.math_trainer_sessions force row level security;

alter table public.math_trainer_solve_times enable row level security;
alter table public.math_trainer_solve_times force row level security;

alter table public.math_trainer_wrong_answers enable row level security;
alter table public.math_trainer_wrong_answers force row level security;

alter table public.user_module_state enable row level security;
alter table public.user_module_state force row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_migrations' and policyname = 'user_migrations_owner_only'
  ) then
    create policy user_migrations_owner_only
      on public.user_migrations
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_gamification_stats' and policyname = 'user_gamification_stats_owner_only'
  ) then
    create policy user_gamification_stats_owner_only
      on public.user_gamification_stats
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_daily_activity' and policyname = 'user_daily_activity_owner_only'
  ) then
    create policy user_daily_activity_owner_only
      on public.user_daily_activity
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_formula_favorites' and policyname = 'user_formula_favorites_owner_only'
  ) then
    create policy user_formula_favorites_owner_only
      on public.user_formula_favorites
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_dictionary_history' and policyname = 'user_dictionary_history_owner_only'
  ) then
    create policy user_dictionary_history_owner_only
      on public.user_dictionary_history
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_settings' and policyname = 'user_settings_owner_only'
  ) then
    create policy user_settings_owner_only
      on public.user_settings
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'math_trainer_sessions' and policyname = 'math_trainer_sessions_owner_only'
  ) then
    create policy math_trainer_sessions_owner_only
      on public.math_trainer_sessions
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'math_trainer_solve_times' and policyname = 'math_trainer_solve_times_owner_only'
  ) then
    create policy math_trainer_solve_times_owner_only
      on public.math_trainer_solve_times
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'math_trainer_wrong_answers' and policyname = 'math_trainer_wrong_answers_owner_only'
  ) then
    create policy math_trainer_wrong_answers_owner_only
      on public.math_trainer_wrong_answers
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_module_state' and policyname = 'user_module_state_owner_only'
  ) then
    create policy user_module_state_owner_only
      on public.user_module_state
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;
